# Generated by Django 2.2 on 2020-06-27 22:30

from django.db import migrations, models
import legaltec.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=20, verbose_name='Direccion')),
                ('fono', models.CharField(max_length=20, verbose_name='Fono')),
                ('mail', models.CharField(max_length=20, verbose_name='email')),
                ('poliza', models.FileField(blank=True, null=True, upload_to=legaltec.models.my_awesome_upload_function, verbose_name='Poliza')),
            ],
            options={
                'verbose_name_plural': 'leads',
            },
        ),
    ]
