# Generated by Django 2.2 on 2020-07-01 17:00

from django.db import migrations, models
import legaltec.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aseguradora', models.CharField(max_length=120, verbose_name='Aseguradora')),
            ],
            options={
                'verbose_name_plural': 'Aseguradoras',
            },
        ),
        migrations.CreateModel(
            name='lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=90, verbose_name='Direccion')),
                ('fono', models.CharField(max_length=20, verbose_name='Fono')),
                ('mail', models.CharField(max_length=40, verbose_name='email')),
                ('poliza', models.FileField(blank=True, null=True, upload_to=legaltec.models.my_awesome_upload_function, verbose_name='Poliza')),
                ('extracto', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False, verbose_name='Revisado')),
            ],
            options={
                'verbose_name_plural': 'leads',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=120, verbose_name='Pregunta')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
            },
        ),
    ]
