# Generated by Django 2.2 on 2020-07-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legaltec', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aseguradora',
        ),
    ]
