# Generated by Django 2.2 on 2020-06-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaltec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='mail',
            field=models.CharField(max_length=40, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
