# Generated by Django 2.2 on 2020-06-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legaltec', '0002_auto_20200627_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Revisado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='extracto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='direccion',
            field=models.CharField(max_length=90, verbose_name='Direccion'),
        ),
    ]
