# Generated by Django 2.2 on 2020-07-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legaltec', '0004_preguntas_aseguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='aseguradora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='legaltec.Aseguradora'),
            preserve_default=False,
        ),
    ]
